server:
  port: 8080
  #上下文
  context-path: /thymeleaf

spring:
  mvc:
    servlet:
      load-on-startup: 1
    hiddenmethod:
      filter:
        enabled: true
    #JSP配置
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #thymeleaf 配置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
#    prefix: classpath:/templates/
  #缓存设置为false, 这样修改之后马上生效，便于调试
    cache: false
  http:
    #设置文件上传大小
    multipart: maxFileSize=100Mb
    maxRequestSize: 100Mb
  ###########################redis#########################
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 10
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      #连接池中的最大空闲连接
      max-idle: 8
      #连接池中的最小空闲连接
      min-idle: 0
    #连接超时时间（毫秒）
    imeout: 0




  datasource:
    username: root
    password: 151415
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver





mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.thz.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug